language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-react-coffee-webpack' ]; then cd .. && eval "mv $currentfolder generator-react-coffee-webpack" && cd generator-react-coffee-webpack; fi